spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  profiles:
    active: local

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      #ddl-auto: none / create-drop / create / update / validate
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

logging:
  level:
    root: info
    sql: error
    jdbc: off
    jdbc.sqlonly: debug
    org.springframework.web: DEBUG
  #    org.hibernate.SQL: DEBUG
  #    org.hibernate.type: trace
  file:
    path: /logs

jwt:
  key: 12345678901234567890123456789012

---
# 로컬
spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    #    url: jdbc:h2:~/test; #메모리
    url: jdbc:h2:file:./memoryDb #상대경로 파일저장(memoryDb.mv.db)
    driver-class-name: org.h2.Driver
    username: sa
    password:

server:
  port: 8080

---
# 개발
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:log4jdbc:mariadb://211.43.12.150:13306/hcmp21?verifyServerCertificate=false&useSSL=false
    dirverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      username: hcmp
      password: hcmp54#@
      maximum-pool-size: 10
      connection-test-query: SELECT 1

server:
  port: 8080

---
# 배포
spring:
  config:
    activate:
      on-profile: release

server:
  port: 8080
